/**
 * Preset library. Each preset is a partial state that gets merged on top of
 * the default state (see state.js). Keep these small and readable, they are
 * the "starting points" a user picks from.
 */

const tween = (duration, ease = "easeOut", extra = {}) => ({ type: "tween", duration, ease, ...extra });
const spring = (stiffness, damping, extra = {}) => ({ type: "spring", springMode: "physics", stiffness, damping, ...extra });

export const PRESETS = [
  {
    id: "fade-in",
    name: "Fade in",
    emoji: "🌅",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [{ prop: "opacity", values: [0, 1] }],
      transition: tween(1, "smooth"),
    },
  },
  {
    id: "fade-up",
    name: "Fade up",
    emoji: "⬆️",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "opacity", values: [0, 1] },
        { prop: "y", values: [32, 0] },
        { prop: "blur", values: [6, 0] },
      ],
      transition: tween(0.9, "smooth"),
    },
  },
  {
    id: "slide-left",
    name: "Slide in from left",
    emoji: "➡️",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "x", values: [-160, 0] },
        { prop: "opacity", values: [0, 1] },
      ],
      transition: tween(0.8, "smooth"),
    },
  },
  {
    id: "pop",
    name: "Pop (spring)",
    emoji: "🫧",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "scale", values: [0.4, 1] },
        { prop: "opacity", values: [0, 1] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.5, bounce: 0.35 },
    },
  },
  {
    id: "bounce-in",
    name: "Bounce in",
    emoji: "🏀",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "y", values: [-220, 0] },
        { prop: "opacity", values: [0, 1] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.6, bounce: 0.55 },
    },
  },
  {
    id: "blur-in",
    name: "Blur in",
    emoji: "🌫️",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "blur", values: [10, 0] },
        { prop: "opacity", values: [0, 1] },
        { prop: "scale", values: [1.1, 1] },
      ],
      transition: tween(1.1, "smooth"),
    },
  },
  {
    id: "flip-in",
    name: "3D flip in",
    emoji: "🔄",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "rotateY", values: [-90, 0] },
        { prop: "opacity", values: [0, 1] },
      ],
      transition: tween(0.9, "expoOut"),
    },
  },
  {
    id: "spin-in",
    name: "Spin in",
    emoji: "🌀",
    tags: ["entrance"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "rotate", values: [-180, 0] },
        { prop: "scale", values: [0, 1] },
      ],
      transition: spring(180, 16),
    },
  },
  {
    id: "in-hold-out",
    name: "In, hold, out",
    emoji: "⏱️",
    tags: ["attention"],
    state: {
      trigger: "load",
      element: { type: "card" },
      tracks: [
        { prop: "opacity", values: [0, 1, 1, 0], times: [0, 0.12, 0.85, 1] },
        { prop: "y", values: [30, 0, 0, -20], times: [0, 0.12, 0.85, 1] },
      ],
      transition: tween(3.5, "easeInOut"),
    },
  },
  {
    id: "pulse",
    name: "Pulse (loop)",
    emoji: "💓",
    tags: ["loop"],
    state: {
      trigger: "load",
      tracks: [{ prop: "scale", values: [1, 1.12, 1] }],
      transition: tween(1.2, "easeInOut", { infinite: true, repeatType: "loop" }),
    },
  },
  {
    id: "float",
    name: "Float (loop)",
    emoji: "🎈",
    tags: ["loop"],
    state: {
      trigger: "load",
      tracks: [{ prop: "y", values: [0, -18] }],
      transition: tween(1.6, "easeInOut", { infinite: true, repeatType: "reverse" }),
    },
  },
  {
    id: "shake",
    name: "Shake",
    emoji: "🫨",
    tags: ["attention"],
    state: {
      trigger: "load",
      tracks: [{ prop: "x", values: [0, -14, 14, -10, 10, -6, 6, 0] }],
      transition: tween(0.6, "easeInOut"),
    },
  },
  {
    id: "wobble",
    name: "Wobble",
    emoji: "🪀",
    tags: ["attention"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "rotate", values: [0, -8, 8, -6, 6, -3, 3, 0] },
        { prop: "scale", values: [1, 1.05, 1] },
      ],
      transition: tween(0.9, "easeInOut"),
    },
  },
  {
    id: "color-shift",
    name: "Color shift (loop)",
    emoji: "🎨",
    tags: ["loop"],
    state: {
      trigger: "load",
      tracks: [
        { prop: "backgroundColor", values: ["#7c3aed", "#ec4899", "#f59e0b", "#7c3aed"] },
        { prop: "borderRadius", values: [16, 60, 16, 16] },
      ],
      transition: tween(4, "linear", { infinite: true, repeatType: "loop" }),
    },
  },
  {
    id: "pointer-tilt",
    name: "3D tilt card (follows pointer)",
    emoji: "🃏",
    tags: ["interaction"],
    state: {
      trigger: "pointer",
      element: { type: "card" },
      pointer: { area: "element", perspective: 900 },
      tracks: [
        { prop: "rotateX", axis: "y", values: [10, -10] },
        { prop: "rotateY", axis: "x", values: [-10, 10] },
        { prop: "scale", axis: "enter", values: [1, 1.04] },
        { prop: "shadow", axis: "enter", values: [0, 44] },
      ],
      transition: spring(260, 28),
    },
  },
  {
    id: "magnetic-button",
    name: "Magnetic button",
    emoji: "🧲",
    tags: ["interaction"],
    state: {
      trigger: "pointer",
      element: { type: "button", text: "Get started" },
      pointer: { area: "element", perspective: 900 },
      tracks: [
        { prop: "x", axis: "x", values: [-14, 14] },
        { prop: "y", axis: "y", values: [-10, 10] },
        { prop: "scale", axis: "enter", values: [1, 1.08] },
      ],
      transition: spring(320, 22),
    },
  },
  {
    id: "hover-lift",
    name: "Hover lift",
    emoji: "🖱️",
    tags: ["interaction"],
    state: {
      trigger: "hover",
      element: { type: "card" },
      tracks: [
        { prop: "y", values: [0, -8] },
        { prop: "scale", values: [1, 1.02] },
        { prop: "shadow", values: [0, 36] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.35, bounce: 0.2 },
    },
  },
  {
    id: "hover-tilt",
    name: "Hover tilt",
    emoji: "🃏",
    tags: ["interaction"],
    state: {
      trigger: "hover",
      element: { type: "card" },
      tracks: [
        { prop: "rotateX", values: [0, 10] },
        { prop: "rotateY", values: [0, -10] },
        { prop: "scale", values: [1, 1.04] },
      ],
      transition: tween(0.45, "smooth"),
    },
  },
  {
    id: "press-squish",
    name: "Press squish",
    emoji: "👇",
    tags: ["interaction"],
    state: {
      trigger: "press",
      element: { type: "button" },
      tracks: [{ prop: "scale", values: [1, 0.94] }],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.25, bounce: 0.3 },
    },
  },
  {
    id: "reveal-scroll",
    name: "Reveal on scroll",
    emoji: "📜",
    tags: ["scroll"],
    state: {
      trigger: "inView",
      element: { type: "card" },
      tracks: [
        { prop: "opacity", values: [0, 1] },
        { prop: "y", values: [48, 0] },
        { prop: "blur", values: [8, 0] },
      ],
      transition: tween(1, "smooth"),
      inView: { amount: 0.4, once: false },
    },
  },
  {
    id: "stagger-list",
    name: "Stagger list",
    emoji: "📋",
    tags: ["entrance"],
    state: {
      trigger: "load",
      element: { type: "list", count: 5 },
      tracks: [
        { prop: "opacity", values: [0, 1] },
        { prop: "y", values: [24, 0] },
        { prop: "blur", values: [4, 0] },
      ],
      transition: tween(0.7, "smooth"),
      stagger: { enabled: true, each: 0.07, from: "first" },
    },
  },
  {
    id: "stagger-pop",
    name: "Stagger pop from center",
    emoji: "✨",
    tags: ["entrance"],
    state: {
      trigger: "load",
      element: { type: "list", count: 6 },
      tracks: [
        { prop: "scale", values: [0.7, 1] },
        { prop: "opacity", values: [0, 1] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.5, bounce: 0.3 },
      stagger: { enabled: true, each: 0.06, from: "center" },
    },
  },
  {
    id: "mask-words",
    name: "Words slide up (masked)",
    emoji: "🎞️",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Design motion, ship code.", split: "words", mask: true },
      tracks: [{ prop: "yPercent", values: [135, 0] }],
      transition: tween(0.95, "expoOut"),
      stagger: { enabled: true, each: 0.08, from: "first" },
    },
  },
  {
    id: "mask-letters",
    name: "Letters slide up (masked)",
    emoji: "🔡",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Motion that moves", split: "chars", mask: true },
      tracks: [{ prop: "yPercent", values: [135, 0] }],
      transition: tween(0.85, "expoOut"),
      stagger: { enabled: true, each: 0.035, from: "first" },
    },
  },
  {
    id: "words-rise",
    name: "Words rise",
    emoji: "🔤",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Design motion, ship code.", split: "words" },
      tracks: [
        { prop: "opacity", values: [0, 1] },
        { prop: "y", values: [24, 0] },
        { prop: "blur", values: [6, 0] },
      ],
      transition: tween(0.8, "smooth"),
      stagger: { enabled: true, each: 0.08, from: "first" },
    },
  },
  {
    id: "letters-drop",
    name: "Letters drop in",
    emoji: "🅰️",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Hello there", split: "chars" },
      tracks: [
        { prop: "y", values: [-60, 0] },
        { prop: "opacity", values: [0, 1] },
        { prop: "rotate", values: [-12, 0] },
      ],
      transition: spring(260, 16),
      stagger: { enabled: true, each: 0.04, from: "first" },
    },
  },
  {
    id: "letters-scale",
    name: "Letters from center",
    emoji: "🔠",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "MOTION", split: "chars" },
      tracks: [
        { prop: "scale", values: [0, 1] },
        { prop: "opacity", values: [0, 1] },
        { prop: "y", values: [18, 0] },
      ],
      transition: tween(0.7, "backOut"),
      stagger: { enabled: true, each: 0.06, from: "center" },
    },
  },
  {
    id: "typewriter",
    name: "Typewriter reveal",
    emoji: "⌨️",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Typing this out, one letter at a time.", split: "chars" },
      tracks: [{ prop: "opacity", values: [0, 1] }],
      transition: tween(0.01, "linear"),
      stagger: { enabled: true, each: 0.045, from: "first" },
    },
  },
  {
    id: "words-blur-scroll",
    name: "Words blur in on scroll",
    emoji: "🌁",
    tags: ["text", "scroll"],
    state: {
      trigger: "inView",
      element: { type: "text", text: "Scroll to reveal every word.", split: "words" },
      tracks: [
        { prop: "opacity", values: [0, 1] },
        { prop: "blur", values: [10, 0] },
        { prop: "scale", values: [0.9, 1] },
      ],
      transition: tween(0.9, "smooth"),
      stagger: { enabled: true, each: 0.1, from: "first" },
      inView: { amount: 0.5, once: false },
    },
  },
  {
    id: "letters-flip",
    name: "Letters flip in",
    emoji: "🎴",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Flip it", split: "chars" },
      tracks: [
        { prop: "rotateX", values: [-90, 0] },
        { prop: "opacity", values: [0, 1] },
        { prop: "y", values: [20, 0] },
      ],
      transition: tween(0.7, "backOut"),
      stagger: { enabled: true, each: 0.06, from: "first" },
    },
  },
  {
    id: "letters-slam",
    name: "Letters slam in",
    emoji: "💥",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "IMPACT", split: "chars" },
      tracks: [
        { prop: "scale", values: [3, 1] },
        { prop: "opacity", values: [0, 1] },
        { prop: "blur", values: [10, 0] },
      ],
      transition: tween(0.55, "expoOut"),
      stagger: { enabled: true, each: 0.07, from: "first" },
    },
  },
  {
    id: "words-skew",
    name: "Words skew slide",
    emoji: "🪂",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Fast, fluid, effortless.", split: "words" },
      tracks: [
        { prop: "x", values: [-60, 0] },
        { prop: "skewX", values: [25, 0] },
        { prop: "opacity", values: [0, 1] },
      ],
      transition: tween(0.8, "smooth"),
      stagger: { enabled: true, each: 0.1, from: "first" },
    },
  },
  {
    id: "words-from-right",
    name: "Words from the right",
    emoji: "⬅️",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Read this backwards", split: "words" },
      tracks: [
        { prop: "x", values: [40, 0] },
        { prop: "opacity", values: [0, 1] },
        { prop: "rotateY", values: [60, 0] },
      ],
      transition: spring(220, 22),
      stagger: { enabled: true, each: 0.1, from: "last" },
    },
  },
  {
    id: "cinematic-title",
    name: "Cinematic title",
    emoji: "🎬",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "text", text: "THE STUDIO", split: "none" },
      tracks: [
        { prop: "opacity", values: [0, 1] },
        { prop: "blur", values: [10, 0] },
        { prop: "scale", values: [1.2, 1] },
        { prop: "y", values: [14, 0] },
      ],
      transition: tween(1.6, "expoOut"),
    },
  },
  {
    id: "letters-wave",
    name: "Wave (loop)",
    emoji: "🌊",
    tags: ["text", "loop"],
    state: {
      trigger: "load",
      element: { type: "text", text: "wavy text", split: "chars" },
      tracks: [{ prop: "y", values: [0, -14, 0] }],
      transition: tween(0.7, "easeInOut", { infinite: true, repeatType: "loop", repeatDelay: 0.6 }),
      stagger: { enabled: true, each: 0.05, from: "first" },
    },
  },
  {
    id: "letters-rainbow",
    name: "Rainbow letters (loop)",
    emoji: "🌈",
    tags: ["text", "loop"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Colorful", split: "chars" },
      tracks: [
        { prop: "color", values: ["#8b5cf6", "#ec4899", "#f59e0b", "#22c55e", "#8b5cf6"] },
        { prop: "scale", values: [1, 1.15, 1, 1, 1] },
      ],
      transition: tween(2.4, "linear", { infinite: true, repeatType: "loop" }),
      stagger: { enabled: true, each: 0.12, from: "first" },
    },
  },
  {
    id: "letters-jump-hover",
    name: "Hover: letters jump",
    emoji: "🐇",
    tags: ["text", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "text", text: "Hover me", split: "chars" },
      tracks: [
        { prop: "y", values: [0, -14] },
        { prop: "scale", values: [1, 1.25] },
        { prop: "color", values: ["auto", "#ec4899"] },
      ],
      transition: spring(400, 14),
    },
  },
  {
    id: "heading-spread-hover",
    name: "Hover: heading swell",
    emoji: "🫧",
    tags: ["text", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "text", text: "Swell up", split: "none" },
      tracks: [
        { prop: "scale", values: [1, 1.06] },
        { prop: "y", values: [0, -3] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.35, bounce: 0.3 },
    },
  },
  {
    id: "grid-cascade",
    name: "Grid cascade",
    emoji: "🧱",
    tags: ["multiple"],
    state: {
      trigger: "load",
      element: { type: "grid", count: 9 },
      tracks: [
        { prop: "opacity", values: [0, 1] },
        { prop: "scale", values: [0.85, 1] },
        { prop: "y", values: [24, 0] },
      ],
      transition: tween(0.8, "smooth"),
      stagger: { enabled: true, each: 0.05, from: "first" },
    },
  },
  {
    id: "grid-ripple",
    name: "Grid ripple from center",
    emoji: "🌊",
    tags: ["multiple", "loop"],
    state: {
      trigger: "load",
      element: { type: "grid", count: 9 },
      tracks: [
        { prop: "scale", values: [1, 0.75, 1] },
        { prop: "opacity", values: [1, 0.55, 1] },
      ],
      transition: tween(1.4, "easeInOut", { infinite: true, repeatType: "loop", repeatDelay: 0.4 }),
      stagger: { enabled: true, each: 0.08, from: "center" },
    },
  },
  {
    id: "list-flip-in",
    name: "List 3D flip in",
    emoji: "🗂️",
    tags: ["multiple"],
    state: {
      trigger: "load",
      element: { type: "list", count: 5 },
      tracks: [
        { prop: "rotateX", values: [-90, 0] },
        { prop: "opacity", values: [0, 1] },
        { prop: "y", values: [20, 0] },
      ],
      transition: tween(0.7, "backOut"),
      stagger: { enabled: true, each: 0.1, from: "first" },
    },
  },
  {
    id: "scroll-spin",
    name: "Scroll-linked spin",
    emoji: "🎚️",
    tags: ["scroll"],
    state: {
      trigger: "scroll",
      tracks: [
        { prop: "rotate", values: [0, 360] },
        { prop: "borderRadius", values: [16, 60] },
      ],
      transition: tween(1, "linear"),
      scroll: { offsetStart: "start end", offsetEnd: "end start" },
    },
  },
  {
    id: "scroll-grow",
    name: "Scroll-linked grow",
    emoji: "📈",
    tags: ["scroll"],
    state: {
      trigger: "scroll",
      element: { type: "text" },
      tracks: [
        { prop: "scale", values: [0.6, 1.3] },
        { prop: "opacity", values: [0.2, 1] },
        { prop: "blur", values: [8, 0] },
      ],
      transition: tween(1, "linear"),
      scroll: { offsetStart: "start end", offsetEnd: "center center" },
    },
  },

  /* --- UI components ------------------------------------------------------ */
  {
    id: "c-tilt-card",
    name: "3D tilt card · glare & depth",
    emoji: "🎴",
    tags: ["component", "interaction"],
    state: {
      trigger: "pointer",
      element: { type: "tiltcard" },
      pointer: { area: "element", perspective: 900 },
      tracks: [
        { part: "root", prop: "rotateX", axis: "y", values: [10, -10] },
        { part: "root", prop: "rotateY", axis: "x", values: [-10, 10] },
        { part: "root", prop: "scale", axis: "enter", values: [1, 1.03] },
        { part: "spot", prop: "x", axis: "x", values: [-140, 140] },
        { part: "spot", prop: "y", axis: "y", values: [-140, 140] },
        { part: "spot", prop: "opacity", axis: "enter", values: [0, 1] },
        { part: "media", prop: "z", axis: "enter", values: [0, 14] },
        { part: "media", prop: "x", axis: "x", values: [-5, 5] },
        { part: "media", prop: "y", axis: "y", values: [-5, 5] },
        { part: "badge", prop: "z", axis: "enter", values: [0, 30] },
        { part: "title", prop: "z", axis: "enter", values: [0, 24] },
      ],
      transition: spring(260, 28),
    },
  },
  {
    id: "c-spotlight",
    name: "Spotlight card",
    emoji: "🔦",
    tags: ["component", "interaction"],
    state: {
      trigger: "pointer",
      element: { type: "spotlight" },
      pointer: { area: "element", perspective: 900 },
      tracks: [
        { part: "root", prop: "scale", axis: "enter", values: [1, 1.015] },
        { part: "glow", prop: "x", axis: "x", values: [-150, 150] },
        { part: "glow", prop: "y", axis: "y", values: [-90, 90] },
        { part: "glow", prop: "opacity", axis: "enter", values: [0, 1] },
      ],
      transition: spring(300, 30),
    },
  },
  {
    id: "c-parallax",
    name: "Mouse parallax layers",
    emoji: "🪟",
    tags: ["component", "interaction"],
    state: {
      trigger: "pointer",
      element: { type: "parallax" },
      pointer: { area: "scene", perspective: 900 },
      tracks: [
        { part: "back", prop: "x", axis: "x", values: [30, -30] },
        { part: "back", prop: "y", axis: "y", values: [22, -22] },
        { part: "mid", prop: "x", axis: "x", values: [-22, 22] },
        { part: "mid", prop: "y", axis: "y", values: [-16, 16] },
        { part: "front", prop: "x", axis: "x", values: [-46, 46] },
        { part: "front", prop: "y", axis: "y", values: [-32, 32] },
        { part: "content", prop: "x", axis: "x", values: [8, -8] },
        { part: "content", prop: "y", axis: "y", values: [6, -6] },
      ],
      transition: spring(120, 24),
    },
  },
  {
    id: "c-flip",
    name: "Flip card",
    emoji: "🪪",
    tags: ["component", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "flipcard" },
      tracks: [{ part: "root", prop: "rotateY", values: [0, 180] }],
      transition: tween(0.8, "smooth"),
    },
  },
  {
    id: "c-image-card",
    name: "Image card reveal",
    emoji: "🖼️",
    tags: ["component", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "imagecard" },
      tracks: [
        { part: "image", prop: "scale", values: [1, 1.1] },
        { part: "shade", prop: "opacity", values: [0, 1] },
        { part: "caption", prop: "y", values: [16, 0] },
        { part: "caption", prop: "opacity", values: [0, 1] },
      ],
      transition: tween(0.7, "smooth"),
    },
  },
  {
    id: "c-link-arrow",
    name: "Link: underline & arrow",
    emoji: "↗️",
    tags: ["component", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "linkarrow" },
      tracks: [
        { part: "line", prop: "scaleX", values: [0, 1] },
        { part: "arrow", prop: "x", values: [-10, 0] },
        { part: "arrow", prop: "opacity", values: [0, 1] },
      ],
      transition: tween(0.45, "smooth"),
    },
  },
  {
    id: "c-fill-button",
    name: "Fill sweep button",
    emoji: "🌊",
    tags: ["component", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "fillbtn" },
      tracks: [{ part: "fill", prop: "xPercent", values: [-101, 0] }],
      transition: tween(0.5, "smooth"),
    },
  },
  {
    id: "c-dock",
    name: "Dock magnify",
    emoji: "🧲",
    tags: ["interaction"],
    state: {
      trigger: "pointer",
      element: { type: "dock" },
      pointer: { area: "element", perspective: 900, radius: 100 },
      tracks: [
        { part: "item", prop: "scale", axis: "near", values: [1, 1.4] },
        { part: "item", prop: "y", axis: "near", values: [0, -6] },
      ],
      transition: spring(480, 30),
    },
  },
  {
    id: "c-compare",
    name: "Image comparison slider",
    emoji: "↔️",
    tags: ["interaction"],
    state: {
      trigger: "pointer",
      element: { type: "compare" },
      pointer: { area: "element", perspective: 900, radius: 120, hold: true },
      tracks: [
        { part: "after", prop: "clipRight", axis: "x", values: [100, 0] },
        { part: "handle", prop: "xPercent", axis: "x", values: [-100, 0] },
      ],
      transition: spring(600, 42),
    },
  },
  {
    id: "c-popover",
    name: "Morphing popover",
    emoji: "💬",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "popover" },
      tracks: [
        { part: "surface", prop: "width", values: [140, 300] },
        { part: "surface", prop: "height", values: [46, 190] },
        { part: "surface", prop: "borderRadius", values: [23, 18] },
        { part: "btn", prop: "opacity", values: [1, 0, 0], times: [0, 0.3, 1] },
        { part: "form", prop: "opacity", values: [0, 0, 1], times: [0, 0.5, 1] },
      ],
      transition: tween(0.5, "smooth"),
    },
  },
  {
    id: "c-toolbar",
    name: "Expandable toolbar",
    emoji: "🧰",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "toolbar" },
      tracks: [
        { part: "root", prop: "width", values: [48, 208] },
        { part: "toggle", prop: "rotate", values: [0, 45] },
        { part: "tool", prop: "opacity", values: [0, 1] },
        { part: "tool", prop: "scale", values: [0.5, 1] },
      ],
      transition: spring(520, 34),
      stagger: { enabled: true, each: 0.03, from: "first" },
    },
  },
  {
    id: "c-marquee",
    name: "Infinite slider (marquee)",
    emoji: "♾️",
    tags: ["effect"],
    state: {
      trigger: "load",
      element: { type: "marquee" },
      tracks: [{ part: "track", prop: "xPercent", values: [0, -50] }],
      transition: tween(12, "linear", { infinite: true, repeatType: "loop" }),
    },
  },
  {
    id: "c-border-trail",
    name: "Border trail",
    emoji: "✨",
    tags: ["effect"],
    state: {
      trigger: "load",
      element: { type: "bordertrail" },
      tracks: [{ part: "spin", prop: "rotate", values: [0, 360] }],
      transition: tween(3, "linear", { infinite: true, repeatType: "loop" }),
    },
  },
  {
    id: "c-glow",
    name: "Glow card",
    emoji: "🌈",
    tags: ["effect"],
    state: {
      trigger: "load",
      element: { type: "glow" },
      tracks: [{ part: "spin", prop: "rotate", values: [0, 360] }],
      transition: tween(6, "linear", { infinite: true, repeatType: "loop" }),
    },
  },
  {
    id: "c-counter",
    name: "Animated number (count up)",
    emoji: "🔢",
    tags: ["effect"],
    state: {
      trigger: "inView",
      element: { type: "counter" },
      tracks: [{ part: "value", prop: "count", values: [0, 2480] }],
      transition: tween(1.6, "easeOut"),
    },
  },
  {
    id: "c-shimmer",
    name: "Shimmer text",
    emoji: "🪩",
    tags: ["text", "loop"],
    state: {
      trigger: "load",
      element: { type: "shimmer" },
      tracks: [{ part: "root", prop: "bgShift", values: [100, 0] }],
      transition: tween(2.4, "linear", { infinite: true, repeatType: "loop" }),
    },
  },
  {
    id: "c-text-loop",
    name: "Text loop (rotating words)",
    emoji: "🔁",
    tags: ["text", "loop"],
    state: {
      trigger: "load",
      element: { type: "textloop" },
      tracks: [
        { part: "word", prop: "yPercent", values: [110, 0, 0, -110, -110], times: [0, 0.06, 0.25, 0.31, 1] },
        { part: "word", prop: "opacity", values: [0, 1, 1, 0, 0], times: [0, 0.06, 0.25, 0.31, 1] },
      ],
      transition: tween(8, "swift", { infinite: true, repeatType: "loop" }),
      stagger: { enabled: true, each: 2, from: "first" },
    },
  },
  {
    id: "c-text-roll",
    name: "Text roll (hover)",
    emoji: "🎰",
    tags: ["text", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "roll" },
      tracks: [
        { part: "a", prop: "yPercent", values: [0, -100] },
        { part: "b", prop: "yPercent", values: [100, 0] },
      ],
      transition: tween(0.4, "smooth"),
      stagger: { enabled: true, each: 0.012, from: "first" },
    },
  },
  {
    id: "c-spin-text",
    name: "Spinning text ring",
    emoji: "🌀",
    tags: ["text", "loop"],
    state: {
      trigger: "load",
      element: { type: "spintext" },
      tracks: [{ part: "root", prop: "rotate", values: [0, 360] }],
      transition: tween(14, "linear", { infinite: true, repeatType: "loop" }),
    },
  },
  {
    id: "text-scramble",
    name: "Text scramble",
    emoji: "🔤",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "scramble", text: "Motion Studio" },
      scramble: { chars: "letters" },
      tracks: [],
      transition: tween(1.4, "easeOut"),
    },
  },
  {
    id: "text-scramble-hover",
    name: "Scramble on hover",
    emoji: "🧬",
    tags: ["text", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "scramble", text: "Hover me" },
      scramble: { chars: "symbols" },
      tracks: [],
      transition: tween(0.9, "easeOut"),
    },
  },
  {
    id: "text-shimmer-wave",
    name: "Shimmer wave (letters)",
    emoji: "🌊",
    tags: ["text", "loop"],
    state: {
      trigger: "load",
      element: { type: "text", text: "Shimmer wave", split: "chars" },
      tracks: [{ prop: "color", values: ["#8b8b95", "#7c3aed", "#8b8b95"] }],
      transition: tween(1.6, "easeInOut", { infinite: true, repeatType: "loop" }),
      stagger: { enabled: true, each: 0.07, from: "first" },
    },
  },
  {
    id: "c-copy",
    name: "Copy button (icon swap)",
    emoji: "📋",
    tags: ["component"],
    state: {
      trigger: "toggle",
      toggle: { autoClose: 2 },
      element: { type: "copybtn" },
      tracks: [
        { part: "bg", prop: "opacity", values: [0, 1] },
        { part: "bg", prop: "scale", values: [0.6, 1] },
        { part: "copy", prop: "opacity", values: [1, 0] },
        { part: "copy", prop: "scale", values: [1, 0.4] },
        { part: "check", prop: "opacity", values: [0, 1] },
        { part: "check", prop: "scale", values: [0.4, 1] },
        { part: "tick", prop: "draw", values: [0, 1] },
      ],
      transition: spring(520, 34),
    },
  },
  {
    id: "c-hold",
    name: "Hold to confirm",
    emoji: "👆",
    tags: ["interaction"],
    state: {
      trigger: "press",
      element: { type: "holdbtn" },
      tracks: [{ part: "fill", prop: "scaleX", values: [0, 1] }],
      transition: tween(1.1, "linear"),
    },
  },
  {
    id: "c-stack",
    name: "Card stack (fans out)",
    emoji: "🃏",
    tags: ["interaction"],
    state: {
      trigger: "hover",
      element: { type: "cardstack" },
      tracks: [
        { part: "c1", prop: "y", values: [0, -10] },
        { part: "c1", prop: "scale", values: [1, 1.03] },
        { part: "c2", prop: "x", values: [0, -86] },
        { part: "c2", prop: "y", values: [-12, -4] },
        { part: "c2", prop: "rotate", values: [0, -9] },
        { part: "c2", prop: "scale", values: [0.94, 1] },
        { part: "c3", prop: "x", values: [0, 86] },
        { part: "c3", prop: "y", values: [-24, -4] },
        { part: "c3", prop: "rotate", values: [0, 9] },
        { part: "c3", prop: "scale", values: [0.88, 1] },
      ],
      transition: spring(300, 26),
    },
  },
  {
    id: "c-radial",
    name: "Radial menu",
    emoji: "🎡",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "radial" },
      tracks: [
        { part: "toggle", prop: "rotate", values: [0, 45] },
        { part: "item", prop: "x", values: [0, 100] },
        { part: "item", prop: "scale", values: [0.4, 1] },
        { part: "item", prop: "opacity", values: [0, 1] },
      ],
      transition: spring(420, 26),
      stagger: { enabled: true, each: 0.04, from: "first" },
    },
  },
  {
    id: "c-palette",
    name: "Command palette",
    emoji: "⌘",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "palette" },
      tracks: [
        { part: "backdrop", prop: "opacity", values: [0, 1] },
        { part: "panel", prop: "opacity", values: [0, 1] },
        { part: "panel", prop: "scale", values: [0.96, 1] },
        { part: "panel", prop: "y", values: [-12, 0] },
        { part: "item", prop: "opacity", values: [0, 1] },
        { part: "item", prop: "y", values: [8, 0] },
      ],
      transition: spring(480, 34),
      stagger: { enabled: true, each: 0.035, from: "first" },
    },
  },
  {
    id: "c-ripples",
    name: "Ripple loader",
    emoji: "🌊",
    tags: ["effect"],
    state: {
      trigger: "load",
      element: { type: "ripples" },
      tracks: [
        { part: "ring", prop: "scale", values: [0.25, 1] },
        { part: "ring", prop: "opacity", values: [0.9, 0] },
      ],
      transition: tween(1.8, "easeOut", { infinite: true, repeatType: "loop" }),
      stagger: { enabled: true, each: 0.6, from: "first" },
    },
  },
  {
    id: "c-pathdraw",
    name: "Path drawing (loop)",
    emoji: "✍️",
    tags: ["effect"],
    state: {
      trigger: "load",
      element: { type: "pathdraw" },
      tracks: [{ part: "line", prop: "draw", values: [0, 1] }],
      transition: tween(1.6, "easeInOut", { infinite: true, repeatType: "reverse", repeatDelay: 0.3 }),
    },
  },
  {
    id: "c-cursor",
    name: "Cursor follower",
    emoji: "⭕",
    tags: ["interaction"],
    state: {
      trigger: "pointer",
      element: { type: "cursorring" },
      pointer: { area: "scene", perspective: 900, radius: 120, hold: false },
      tracks: [
        { part: "root", prop: "x", axis: "cursorX", values: [0, 1] },
        { part: "root", prop: "y", axis: "cursorY", values: [0, 1] },
        { part: "root", prop: "scale", axis: "enter", values: [0.8, 1.4] },
      ],
      transition: spring(280, 26),
    },
  },
  {
    id: "c-blinds",
    name: "Page transition: blinds",
    emoji: "🪟",
    tags: ["effect"],
    state: {
      trigger: "toggle",
      element: { type: "blinds" },
      tracks: [{ part: "strip", prop: "scaleY", values: [0, 1] }],
      transition: tween(0.55, "swift"),
      stagger: { enabled: true, each: 0.06, from: "first" },
    },
  },
  {
    id: "c-iris",
    name: "Page transition: iris",
    emoji: "👁️",
    tags: ["effect"],
    state: {
      trigger: "toggle",
      element: { type: "iris" },
      tracks: [{ part: "cover", prop: "clipCircle", values: [0, 75] }],
      transition: tween(0.8, "expoOut"),
    },
  },
  {
    id: "c-fill-text",
    name: "Fill text (loading)",
    emoji: "🖍️",
    tags: ["text", "loop"],
    state: {
      trigger: "load",
      element: { type: "filltext" },
      tracks: [{ part: "root", prop: "bgShift", values: [100, 0] }],
      transition: tween(2.2, "easeInOut", { infinite: true, repeatType: "loop", repeatDelay: 0.6 }),
    },
  },
  {
    id: "bobble-hover",
    name: "Bobble hover (bouncy)",
    emoji: "🫧",
    tags: ["interaction"],
    state: {
      trigger: "hover",
      element: { type: "card" },
      tracks: [
        { prop: "scale", values: [1, 1.08] },
        { prop: "rotate", values: [0, -3] },
        { prop: "y", values: [0, -6] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.5, bounce: 0.55 },
    },
  },
  {
    id: "scroll-image-reveal",
    name: "Scroll image reveal",
    emoji: "🖼️",
    tags: ["scroll"],
    state: {
      trigger: "scroll",
      element: { type: "card" },
      tracks: [
        { prop: "clipTop", values: [70, 0] },
        { prop: "scale", values: [1.25, 1] },
      ],
      transition: tween(1, "linear"),
      scroll: { offsetStart: "start end", offsetEnd: "center center" },
    },
  },
  {
    id: "scroll-zoom-hero",
    name: "Scroll zoom hero",
    emoji: "🔭",
    tags: ["scroll"],
    state: {
      trigger: "scroll",
      element: { type: "card" },
      tracks: [
        { prop: "scale", values: [1, 1.6] },
        { prop: "blur", values: [0, 8] },
        { prop: "opacity", values: [1, 0.15] },
      ],
      transition: tween(1, "linear"),
      scroll: { offsetStart: "center center", offsetEnd: "end start" },
    },
  },
  {
    id: "text-scramble-center",
    name: "Scramble from the middle",
    emoji: "🎯",
    tags: ["text"],
    state: {
      trigger: "load",
      element: { type: "scramble", text: "Awwwards worthy" },
      scramble: { chars: "symbols", order: "center" },
      tracks: [],
      transition: tween(1.6, "easeOut"),
    },
  },
  {
    id: "c-hamburger",
    name: "Hamburger → X",
    emoji: "🍔",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "hamburger" },
      tracks: [
        { part: "bar-top", prop: "y", values: [0, 8] },
        { part: "bar-top", prop: "rotate", values: [0, 45] },
        { part: "bar-mid", prop: "opacity", values: [1, 0] },
        { part: "bar-mid", prop: "scaleX", values: [1, 0.2] },
        { part: "bar-bot", prop: "y", values: [0, -8] },
        { part: "bar-bot", prop: "rotate", values: [0, -45] },
      ],
      transition: spring(420, 26),
    },
  },
  {
    id: "c-dropdown",
    name: "Dropdown menu",
    emoji: "📂",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "dropdown" },
      tracks: [
        { part: "panel", prop: "opacity", values: [0, 1] },
        { part: "panel", prop: "y", values: [-8, 0] },
        { part: "panel", prop: "scale", values: [0.96, 1] },
        { part: "item", prop: "opacity", values: [0, 1] },
        { part: "item", prop: "x", values: [-8, 0] },
        { part: "chevron", prop: "rotate", values: [0, 180] },
      ],
      transition: tween(0.3, "smooth"),
      stagger: { enabled: true, each: 0.03, from: "first" },
    },
  },
  {
    id: "c-modal",
    name: "Modal dialog",
    emoji: "🪟",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "modal" },
      tracks: [
        { part: "backdrop", prop: "opacity", values: [0, 1] },
        { part: "dialog", prop: "opacity", values: [0, 1] },
        { part: "dialog", prop: "scale", values: [0.94, 1] },
        { part: "dialog", prop: "y", values: [12, 0] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.4, bounce: 0.15 },
    },
  },
  {
    id: "c-drawer",
    name: "Side drawer",
    emoji: "🚪",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "drawer" },
      tracks: [
        { part: "backdrop", prop: "opacity", values: [0, 1] },
        { part: "panel", prop: "x", values: [-280, 0] },
        { part: "link", prop: "opacity", values: [0, 1] },
        { part: "link", prop: "x", values: [-24, 0] },
      ],
      transition: tween(0.5, "smooth"),
      stagger: { enabled: true, each: 0.05, from: "first" },
    },
  },
  {
    id: "c-toast",
    name: "Toast notification",
    emoji: "🔔",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "toast" },
      tracks: [
        { part: "card", prop: "opacity", values: [0, 1] },
        { part: "card", prop: "y", values: [20, 0] },
        { part: "card", prop: "scale", values: [0.96, 1] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.45, bounce: 0.3 },
      toggle: { autoClose: 3 },
    },
  },
  {
    id: "c-accordion",
    name: "Accordion",
    emoji: "🪗",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "accordion" },
      tracks: [
        { part: "body", prop: "height", values: [0, 92] },
        { part: "body", prop: "opacity", values: [0, 1] },
        { part: "chevron", prop: "rotate", values: [0, 180] },
      ],
      transition: tween(0.45, "smooth"),
    },
  },
  {
    id: "c-switch",
    name: "Toggle switch",
    emoji: "🎚️",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "switch" },
      tracks: [
        { part: "knob", prop: "x", values: [0, 24] },
        { part: "root", prop: "backgroundColor", values: ["#3f3f50", "#7c3aed"] },
      ],
      transition: spring(500, 32),
    },
  },
  {
    id: "c-tooltip",
    name: "Tooltip",
    emoji: "💬",
    tags: ["component", "interaction"],
    state: {
      trigger: "hover",
      element: { type: "tooltip" },
      tracks: [
        { part: "tip", prop: "opacity", values: [0, 1] },
        { part: "tip", prop: "y", values: [6, 0] },
        { part: "tip", prop: "scale", values: [0.96, 1] },
      ],
      transition: tween(0.25, "smooth"),
    },
  },
  {
    id: "c-fab",
    name: "Floating action menu",
    emoji: "➕",
    tags: ["component"],
    state: {
      trigger: "toggle",
      element: { type: "fab" },
      tracks: [
        { part: "fab", prop: "rotate", values: [0, 45] },
        { part: "action", prop: "opacity", values: [0, 1] },
        { part: "action", prop: "y", values: [16, 0] },
        { part: "action", prop: "scale", values: [0.6, 1] },
      ],
      transition: { type: "spring", springMode: "visual", visualDuration: 0.4, bounce: 0.3 },
      stagger: { enabled: true, each: 0.05, from: "last" },
    },
  },
];

export function findPreset(id) {
  return PRESETS.find((p) => p.id === id);
}
